prefix_mapping = {
    "Española": "Esp_E",
    "Fernandina": "Fer_FE",
    "Floreana": "Flo_FL",
    "Genovesa": "Gen_G",
    "Isabela": "Isa_IS",
    "Marchena": "Mar_M",
    "Pinta": "Pin_P",
    "Pinzón": "Pnz_PZ",
    "Rábida": "Rab_RA",
    "San Cristóbal": "Scris_SR",
    "Santa Cruz": "Scruz_SC",
    "Santa Fe": "SanFe_SF",
    "Santiago": "Snt_ST",
    "Wolf": "Wol_W",
    "Bartolomé (Santiago)": "Snt_BT",
    "Bainbridge (Santiago)": "Snt_BA",
    "Beagles (Santiago)": "Snt_BE",
    "Daphnes (Santa Cruz)": "Scruz_DA",
    "Plazas (Santa Cruz)": "Scruz_PL",
    "Seymour (Santa Cruz)": "Scruz_SE",
}